### ISSUE TITLE
Crash on killing enemy

### ISSUE THREAD

**Issue by frozendragon498** [APengu/ImprovableSkills#6]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre72_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  ISCore (ImprovableSkills_1.12.2-3.1.6r.jar)
  OTGCorePlugin (OTG-Core.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  SoundFixPatchingLoader (AmbientSounds_v2.2.3_mc1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  WTPlugin (WaitingTime-1.0.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/23/18 11:58 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.endie.is.SkillEvents.killEntity(SkillEvents.java:164)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_434_SkillEvents_killEntity_LivingExperienceDropEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:281)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:384)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.endie.is.SkillEvents.killEntity(SkillEvents.java:164)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_434_SkillEvents_killEntity_LivingExperienceDropEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:281)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:384)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.entity.monster.EntitySkeleton)
	Entity ID: 10495
	Entity Name: Skeleton
	Entity's Exact location: -32.74, 79.00, 297.50
	Entity's Block location: World: (-33,79,297), Chunk: (at 15,4,9 in -3,18; contains blocks -48,0,288 to -33,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['uncannyNebula'/2986, l='world', x=-13.73, y=79.00, z=304.26], EntityPlayerMP['frozendragon498'/3027, l='world', x=-27.30, y=49.00, z=301.30]]
	Chunk stats: ServerChunkCache: 514 Drop: 0
	Level seed: -8517886496654018064
	Level generator: ID 06 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (44,63,244), Chunk: (at 12,3,4 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 63462 game time, 63462 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 80713 (now: false), thunder time: 12056 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-103-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1857186352 bytes (1771 MB) / 6227755008 bytes (5939 MB) up to 6227755008 bytes (5939 MB)
	JVM Flags: 2 total; -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 129 mods loaded, 129 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version                  | Source                                           | Signature                                |
	|:--------- |:--------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                   | 9.42                     | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.2.2611-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.2.2611             | forge-1.12.2-14.23.2.2611-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy     | 1.0.0                    | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | itemphysic            | 1.4.0                    | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | littletilescore       | 1.0.0                    | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | otgcore               | 1.12                     | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | movillages            | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| UCHIJAAAA | aether_legacy         | 1.12.2-v2.0              | aether_legacy-1.12.2-v2.0.jar                    | None                                     |
	| UCHIJAAAA | applecore             | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                     | None                                     |
	| UCHIJAAAA | aroma1997core         | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | subcommonlib          | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| UCHIJAAAA | rpginventory          | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                    | None                                     |
	| UCHIJAAAA | beastmaster           | $version                 | beastmaster-1.12.2-1.2.0.1.jar                   | None                                     |
	| UCHIJAAAA | bettermuffling        | 0.2.0-Beta               | Better+Muffling-1.12.2-0.2.0-Beta.jar            | None                                     |
	| UCHIJAAAA | bibliocraft           | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCHIJAAAA | bibliotheca           | 1.2.2-1.12.2             | bibliotheca-1.2.2-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | openterraingenerator  | v4                       | OpenTerrainGenerator-1.12.2+-+v4.jar             | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJAAAA | biomebundle           | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                     | None                                     |
	| UCHIJAAAA | birdsnests            | 2.1.0                    | BirdsNests1.12.2-2.1.0.jar                       | None                                     |
	| UCHIJAAAA | bma_addon             | 1.11.2 4.0.3.0           | bma_addon-1.12-4.1.0.3.jar                       | None                                     |
	| UCHIJAAAA | bonsaitrees           | 1.0.3                    | bonsaitrees-1.0.3-b67.jar                        | None                                     |
	| UCHIJAAAA | bottledmilk           | 1.0.0                    | BottledMilk-1.12-1.1.0.jar                       | None                                     |
	| UCHIJAAAA | bouncing_balls        | 1.5.1.1                  | BouncingBalls-1.12-1.5.1.1.jar                   | None                                     |
	| UCHIJAAAA | cdm                   | 0.2.1                    | device-mod-0.2.1-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | cdmcalculator         | 2.2                      | CalculatorPlus-2.2+(0.2.1).jar                   | None                                     |
	| UCHIJAAAA | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| UCHIJAAAA | chesttransporter      | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                | None                                     |
	| UCHIJAAAA | chisel                | MC1.12-0.1.1.27          | Chisel-MC1.12-0.1.1.27.jar                       | None                                     |
	| UCHIJAAAA | chococraft            | 0.9.1.52                 | chococraft_1.12.1-0.9.1.52.jar                   | None                                     |
	| UCHIJAAAA | coffeespawner         | 1.0.2                    | CoffeeSpawner-1.12-1.0.2.jar                     | None                                     |
	| UCHIJAAAA | cookingforblockheads  | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar           | None                                     |
	| UCHIJAAAA | extendedrenderer      | v1.0                     | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCHIJAAAA | coroutil              | 1.12.1-1.1.24            | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCHIJAAAA | configmod             | v1.0                     | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked | 1.12.2-v1                | CosmeticArmorReworked-1.12.2-v1.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | craftablehorsearmour  | 1.3                      | CraftableHorseArmour-1.3.0-1.12.jar              | None                                     |
	| UCHIJAAAA | creativecore          | 1.9.9                    | CreativeCore_v1.9.18_mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | customspawner         | 3.11.3                   | CustomMobSpawner-3.11.3.jar(1).zip               | None                                     |
	| UCHIJAAAA | dldungeonsjdg         | 1.11.1                   | DoomlikeDungeons-1.11.1-MC1.12.2.jar             | None                                     |
	| UCHIJAAAA | mocreatures           | 12.0.4                   | DrZharks MoCreatures Mod-12.0.4.jar.zip          | None                                     |
	| UCHIJAAAA | idk                   | 4.20.3                   | E-Vaporate-4.20.3.jar                            | None                                     |
	| UCHIJAAAA | elevatorid            | 1.3.5                    | ElevatorMod-1.12.2-1.3.5(1).jar                  | None                                     |
	| UCHIJAAAA | enchantingbottles     | 1.0                      | enchantingbottles-1.0(1).jar                     | None                                     |
	| UCHIJAAAA | csb_ench_table        | 1.1.2                    | EnchantingTable-1.12-1.1.2.jar                   | None                                     |
	| UCHIJAAAA | endercrop             | 1.12-1.3.4               | endercrop-1.12-1.3.4.jar                         | None                                     |
	| UCHIJAAAA | equaldragons          | 1.1                      | EqualDragons-1.1.jar                             | None                                     |
	| UCHIJAAAA | extraalchemy          | 0.3.8-release            | extraalchemy-0.3.8-release.jar                   | None                                     |
	| UCHIJAAAA | farmingforblockheads  | 3.1.5                    | FarmingForBlockheads_1.12-3.1.5.jar              | None                                     |
	| UCHIJAAAA | fasterladderclimbing  | 0.1-127                  | FasterLadderClimbing-1.12-0.1-127.jar            | None                                     |
	| UCHIJAAAA | fenceoverhaul         | 1.3.4                    | FenceOverhaul-1.3.4.jar                          | None                                     |
	| UCHIJAAAA | foamflower            | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1.jar              | None                                     |
	| UCHIJAAAA | friendlyfire          | 1.5.8                    | FriendlyFire-1.12.2-1.5.8.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | cfm                   | 4.1.5                    | furniture-4.1.5-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | gardenstuff           | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                       | None                                     |
	| UCHIJAAAA | giacomos_exp          | 1.2.2                    | GiacomosExperienceSeedling-1.12.2-1.2.2.jar      | None                                     |
	| UCHIJAAAA | giacomos_fishing_net  | 1.6.1                    | GiacomosFishingNet-1.12.2-1.6.1.jar              | None                                     |
	| UCHIJAAAA | giacomosfoundry       | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar                | None                                     |
	| UCHIJAAAA | gps                   | 3.1.1.2                  | GPS-1.12.2-3.1.1.2.jar                           | None                                     |
	| UCHIJAAAA | hammertime            | 2.2.0                    | Hammer+Time-2.2.0-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | hammercore            | 1.9.6.5                  | HammerCore-1.12.2-1.9.6.5.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | harvest               | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                        | None                                     |
	| UCHIJAAAA | placebo               | 1.2.0                    | Placebo-1.12.2-1.2.0.jar                         | None                                     |
	| UCHIJAAAA | hexxitgear            | 2.7.0                    | Hexxit+Gear-1.12.2-2.7.0.jar                     | None                                     |
	| UCHIJAAAA | llibrary              | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | iceandfire            | 1.3.1                    | iceandfire-1.3.1-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | ichunutil             | 7.1.3                    | iChunUtil-1.12.2-7.1.3.jar                       | None                                     |
	| UCHIJAAAA | improvableskills      | 3.1.6r                   | ImprovableSkills_1.12.2-3.1.6r.jar               | None                                     |
	| UCHIJAAAA | inventoryneko         | ${version}               | InventoryNeko-0.1.0.jar                          | None                                     |
	| UCHIJAAAA | inventorypets         | 1.4.9.9b                 | inventorypets-1.12-1.4.9.9b.jar                  | None                                     |
	| UCHIJAAAA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jetorches             | 2.1.0                    | jetorches-1.12.2-2.1.0.jar                       | None                                     |
	| UCHIJAAAA | kleeslabs             | 5.3.2                    | KleeSlabs_1.12-5.3.2.jar                         | None                                     |
	| UCHIJAAAA | littletiles           | 1.5.0                    | LittleTiles_v1.5.0-pre72_mc1.12.2.jar            | None                                     |
	| UCHIJAAAA | magicalmap            | 3.1.0                    | Magical+Map-1.12.2-3.1.0.jar                     | None                                     |
	| UCHIJAAAA | malisiscore           | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                     | None                                     |
	| UCHIJAAAA | malisisblocks         | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                   | None                                     |
	| UCHIJAAAA | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| UCHIJAAAA | malisisswitches       | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                 | None                                     |
	| UCHIJAAAA | mantle                | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCHIJAAAA | melongolem            | 1.1.1                    | MelonMod-1.12-1.1.1.jar                          | None                                     |
	| UCHIJAAAA | memeinabottle         | 2.0.0                    | MemeInABottle-1.12.X-2.0.0.jar                   | None                                     |
	| UCHIJAAAA | mts                   | 9.1.1                    | Minecraft+Transport+Simulator-1.12.2-9.1.1.jar   | None                                     |
	| UCHIJAAAA | testdummy             | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                       | None                                     |
	| UCHIJAAAA | modernlamps           | 1.0.3                    | ModernLights-1.0.3_1.12.jar                      | None                                     |
	| UCHIJAAAA | morph                 | 7.1.1                    | Morph-1.12.2-7.1.1.jar                           | None                                     |
	| UCHIJAAAA | morpheus              | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                          | None                                     |
	| UCHIJAAAA | naturescompass        | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                  | None                                     |
	| UCHIJAAAA | nex                   | 2.1.14.15                | NetherEx-1.12-2.1.14.15.jar                      | None                                     |
	| UCHIJAAAA | nvlforcefields        | 1.12.2.2491.1.0          | nvlforcefields-1.12.2.2491.1.0.jar               | None                                     |
	| UCHIJAAAA | openablewindows       | 0.0.1                    | openablewindows-1.0.jar                          | None                                     |
	| UCHIJAAAA | morepaintings         | $version                 | paintings-1.12.2-3.3.0.0(1).jar                  | None                                     |
	| UCHIJAAAA | guilib                | $version                 | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1(1).jar | None                                     |
	| UCHIJAAAA | paintingselgui        | $version                 | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1(1).jar | None                                     |
	| UCHIJAAAA | getalltheseeds        | 1.12a                    | Pam's+Get+all+the+Seeds!+1.12a.jar               | None                                     |
	| UCHIJAAAA | harvestcraft          | 1.12.2q                  | Pam's+HarvestCraft+1.12.2q.jar                   | None                                     |
	| UCHIJAAAA | petbat                | 1.4.8                    | PetBat-1.12.2.jar                                | None                                     |
	| UCHIJAAAA | playerrevive          | 1.0                      | PlayerRevive+v1.2.10+mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | tconstruct            | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCHIJAAAA | plustic               | 6.3.6.2                  | plustic-6.3.6.2.jar                              | None                                     |
	| UCHIJAAAA | potioncore            | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                    | None                                     |
	| UCHIJAAAA | preston               | 0.3.2                    | Preston-0.3.2.jar                                | None                                     |
	| UCHIJAAAA | quickleafdecay        | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                | None                                     |
	| UCHIJAAAA | xreliquary            | 1.12.2-1.3.4.742         | Reliquary-1.12.2-1.3.4.742.jar                   | None                                     |
	| UCHIJAAAA | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| UCHIJAAAA | secretroomsmod        | 5.3.2                    | secretroomsmod-1.12.2-5.3.2.jar                  | None                                     |
	| UCHIJAAAA | signedit              | 1.12.2-4                 | signedit-1.12.2-5.jar                            | None                                     |
	| UCHIJAAAA | storagenetwork        | 1.12.2-1.2.2             | SimpleStorageNetwork-1.12.2-1.2.2(1).jar         | None                                     |
	| UCHIJAAAA | lteleporters          | 1.12.2-3.0.2             | simpleteleporters-1.12.2-3.0.2.jar               | None                                     |
	| UCHIJAAAA | sophisticatedwolves   | 3.13.2                   | SophisticatedWolves-1.12.2-3.13.2.jar            | None                                     |
	| UCHIJAAAA | spartanshields        | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                  | None                                     |
	| UCHIJAAAA | spiceoflife           | 1.3.11                   | SpiceOfLife-mc1.12-1.3.11.jar                    | None                                     |
	| UCHIJAAAA | statues               | 0.8.1                    | statues-1.12.X-0.8.1.jar                         | None                                     |
	| UCHIJAAAA | stg                   | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                             | None                                     |
	| UCHIJAAAA | thutessentials        | 2.1.6                    | thutessentials-1.12.2-2.1.6.jar                  | None                                     |
	| UCHIJAAAA | totemdefender         | 1.2.8                    | TotemDefender-1.12.2-1.2.8.jar                   | None                                     |
	| UCHIJAAAA | treechopper           | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
	| UCHIJAAAA | umbralux              | 1.12.2                   | umbralux-1.12.2-2.1.0.2.jar                      | None                                     |
	| UCHIJAAAA | vending               | 1.12.2-3.0.1.1           | vending-1.12.2-3.0.1.1.jar                       | None                                     |
	| UCHIJAAAA | vials                 | 1.2.1.4                  | Vials-MC1.12-1.2.1.4.jar                         | None                                     |
	| UCHIJAAAA | waitingtime           | 1.0.0                    | WaitingTime-1.0.0.jar                            | 6919c86a9d8d117dbc520ba31378675eaae1c16a |
	| UCHIJAAAA | waterstrainer         | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                     | None                                     |
	| UCHIJAAAA | weather2              | 1.12.1-2.5.7             | weather2-1.12.1-2.5.7.jar                        | None                                     |
	| UCHIJAAAA | wolfarmor             | 1.12.2-2.1.0-RELEASE     | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar            | None                                     |
	| UCHIJAAAA | worldedit             | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar            | None                                     |
	| UCHIJAAAA | xtones                | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                         | None                                     |
	| UCHIJAAAA | yoyos                 | 1.12.2-1.2.0.18          | yoyos_1.12.2-1.2.0.18.jar                        | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre72_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  
ISCore (ImprovableSkills_1.12.2-3.1.6r.jar)
  com.endie.is.asm.ImprovableSkillsTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SoundFixPatchingLoader (AmbientSounds_v2.2.3_mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
WTPlugin (WaitingTime-1.0.0.jar)
  com.blamejared.waitingtime.core.WTClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['uncannyNebula'/2986, l='world', x=-13.73, y=79.00, z=304.26], EntityPlayerMP['frozendragon498'/3027, l='world', x=-27.30, y=49.00, z=301.30]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by APengu** [comment]
Fixed, next time pls put the whole crash to a pastebin.com.
