### ISSUE TITLE
[1.12.2] Conflict with RPG Inventory's Mining Speed Buff Ring/Cloak.

### ISSUE THREAD

**Issue by Z-Tunic** [APengu/ImprovableSkills#9]
Minecraft: 1.12.2
Forge: 14.23.2.2654

Mods:
HammerCore-1.12.2-1.9.9.1
ImprovableSkills_1.12.2-3.3.2r
rpginventory-1.12-5.3.0.0
subcommonlib-sublib-1.12.2-1.2.0.4
theoneprobe-1.12-1.4.22

-----
This one seems strange as there's two instances where one works but the other one won't and then the other one works but this one doesn't. The instance where it broke RPG Inventory's Mining Speed Buff had other mods installed but before installing Improvable Skills they worked fine.

Anyway... the mod 'RPG Inventory' adds in Necklaces, Rings, Gloves & Cloaks and such which gives you a variety of buffs in a way, such as a increase to your Mining Speed if you wear a 'Buffed Ring' on your Right Hand or a Cloak with 'Emerald Mining Side Lining'.

I am using "The One Probe" which allows me to view the Block Breaking Progress. I also only tap the Left Mouse Button to mine the block  in one tick to get the speeds marked down.

-----
Mods:
HammerCore-1.12.2-1.9.9.1
ImprovableSkills_1.12.2-3.3.2r
theoneprobe-1.12-1.4.22

Using a Diamond Pickaxe on a Stone or Obsidian Block. These are speeds I get in one tick.

Stone
Mining Level 00 - 17%
Mining Level 25 - 73%

Obsidian
Mining Level 00 - 0%
Mining Level 25 - 2%

Now let's add in the mods 'rpginventory-1.12-5.3.0.0 & subcommonlib-sublib-1.12.2-1.2.0.4' and try that again, same set up.

Stone
Mining Level 00 - 17%
Mining Level 25 - 17%

Obsidian
Mining Level 00 - 0%
Mining Level 25 - 0%

Uh-oh, something broke. Now if I wear a 'Buffed Ring' in my Right hand and try that again...

Stone
Mining Level 00 + Mining Speed Buff from Ring - 71%
Mining Level 25 + Mining Speed Buff from Ring - 71%

Obsidian
Mining Level 00 + Mining Speed Buff from Ring - 2%
Mining Level 25 + Mining Speed Buff from Ring - 2%

It seems the Mining Speed Buff from RPG Inventory's Buffed Ring has overwritten the Mining Speed that you can get from the Improvable Skills. I should also mention that the Ring/Cloak affects all speeds for Axes & Shovels, etc. not just Pickaxes Speed if I recall.

-----
https://github.com/ArtixAllMighty/Rpg-Inventory-2016/issues/12
Figure I report it for the other mod, just in case...

**Comment by APengu** [comment]
I will try to fix, but if it won't work, it's not on my end.

**Comment by ArtixAllMighty** [comment]
Quote : 

Thanks for referring the problem as well to the other mod author.
As far as I'm concerned, I do not actually edit anything that is related to mining speed, I just hook into forge's provided BreakSpeed event and add onto the provided speed. 
Any consequent additions from other mods, that add to the breakspeed, should only give more breakspeed, as it would be added multiplicatively , or additively, unless someone sets the given value, instead of adding onto the given value.

https://github.com/ArtixAllMighty/Rpg-Inventory-2016/blob/master/src/main/java/subaraki/rpginventory/handler/JeweleryEffectsHandler.java#L204-L225

````
	private void getEmeraldRingEffect1(BreakSpeed event) {
		if(event.getEntityPlayer() != null)
		{
			RpgInventoryData inventory = RpgInventoryData.get(event.getEntityPlayer());

			ItemStack ring = inventory.getRing_2();

			float modifier = 1;
			float speed = event.getOriginalSpeed();

			if (!ring.isEmpty())				
				if(inventory.getRing_2().getItem().getUnlocalizedName().contains("emerald"))
					modifier = 4;

			float level = (float)cloakLevel(inventory, LootEvent.CLOAK_MINING);

			if(level > 0)
				modifier = modifier == 1 ? level*1.35f : 2 + level * 1.35f;

			event.setNewSpeed(speed*modifier);
		}
	}
````

**Comment by ArtixAllMighty** [comment]
I just checked out your code, it seems we both set our breakspeeds in the same way. 
I'm puzzled as to why this would conflict

**Comment by APengu** [comment]
@ArtixAllMighty I replaced getOriginalSpeed() with getNewSpeed()
